#+TITLE:     Kotlin Tutorial
#+AUTHOR:    Reinhard Braumandl
#+DESCRIPTION: Ein kleines Tutorial zur Programmiersprache Kotlin
#+KEYWORDS:  kotlin, tutorial
#+LANGUAGE:  de
#+OPTIONS:   toc:2
#+OPTIONS: H:4
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-bigblow.setup

* Die Programmiersprache Kotlin

Die Programmiersprache Kotlin wurde von JetBrains im Jahre 2011 vorgestellt.
Die Hauptentwicklung findet in Sankt Petersburg statt und der Name Kotlin stammt
von einer Insel, die vor Sankt Petersburg liegt.

Die Entwickler von Kotlin hatten die Programmiersprache Scala
bezüglich den Programmiersprachen-Features im Blick, wobei Ihnen aber die
Geschwindigkeit des Scala Compilers zu gering und die Kompatibilität
zu Java nicht ausreichend genug waren. Kotlin ist daher keine kleine
Programmiersprache, da versucht wird, möglicht viele Features von Scala
zu realisieren, aber trotzdem kompatibler zu Java zu sein. Das führt zu
relativ vielen Kompromissen und geringerer Orthogonalität bei der Nutzung
von Programmiersprachenkonstrukten. 

Kotlin ist also eher in der Tradition einer Reihe von aktuellen
Programmiersprachen zu sehen, die eher pragmatisch als theoretisch
fundiert und minimalistisch auftreten. Kehrseite der Medaille ist dann
meist, dass die von diesen Programmiersprachen unterstützten
Konstrukte im Laufe der Enwicklung immer weiter ausufern.

Wie schon von neueren Versionen von Java und vor allem Scala bekannt,
ist Kotlin eine objekt-orientierte Programmiersprache, die
verschiedene Anleihen aus den funktionalen Programmiersprachen nimmt.

Besondere Ziele bei der Entwicklung von Kotlin sind:
- Boilerplate Code soll vermieden werden (z.B. mittels Data Classes,
  Default Parameter, Extension Functions, Überladen von Operatoren,
  Typ Inferenz)
- Vermeidung von NullPointerExceptions durch Prüfungen zur
  Compile-Zeit (Null Safety)
- Integration von Konzepten funktionaler Programmiersprachen (Higher
  Order Functions, Pattern Matching, Tail Call Optimization)
- Kompatibilität mit Java


* Zielsetzung

In diesem Tutorial werden wir definitiv nicht alle Details der Sprache
Kotlin vorstellen, sondern versuchen neben dem notwendigen Grundstock
die Features zu vermitteln, die Kotlin auszeichnen und die
unterschiedlich zu Java sind. Wir werden uns auch nur das Java Backend
Einsatzszenario von Kotlin ansehen.

Die Beschreibung der Progammiersprache Kotlin ist auf deren Hauptseite
im Web zu finden: [[https://kotlinlang.org/][Kotlin Hauptseite]] 

Die relativ formale [[https://kotlinlang.org/spec/introduction.html][Definition der Sprache]] gibt im Vergleich zum
größten Teil dieses Webauftritts die präzisere Definition der Sprache
wieder. Bei Zweifeln über bestimmte Konstrukte sollte also die
Sprachdefinition zu Rate gezogen werden.

* Erste Versuche auf der Kommandozeile

Wir starten das Kennenlernen mit der Programmiersprache Kotlin auf
Kommandozeilenebene und nicht gleich in der für Kotlin prädestinierten
IDE IntelliJ. Hierdurch bekommt man eher ein Gefühlt dafür, wie die
Integration mit der Java Plattform realisiert ist - das zumindest ist
unsere Meinung.

Wir nutzen dabei im folgenden eine Linux Installation, um die
Beispiele durchzuspielen. In den Beispielen zeigt der Prompt ~>~ den
Bash Prompt (Linux Shell) an und ~>>>~ den Prompt der Kotlin Shell.

Hierzu müssen wir auf dem Computer des Lesers zunächst das separat
erhältliche Paket mit den Kotlin Kommandozeilen Tools installieren.
Das Paket mit dem Kommandozeilen Compiler ist vom [[https://kotlinlang.org/docs/tutorials/command-line.html][Kotlin Webauftritt]]
zu beziehen, wobei auch eine Anleitung für die Installation gegeben
ist. Das Prozedere der Installation sei als dem Leser überlassen.

Wie auch Java seit Version 9 bietet auch Kotlin die Möglichkeit
Programmkonstrukte in der Kotlin Shell auszuprobieren. Der Aufruf der
Kotlin Shell erfolgt einfach 

Ein minimales und traditionsreiches, erstes Kotlin Programm sieht so
aus:
#+begin_src kotlin :exports none
fun main() {
    println("Hello world")
}
#+end_src
Im Gegensatz zu Java gibt es in Kotlin top-level Funktionen und die
Funktion ~main()~ als ein möglicher Einstiegspunkt eines Kotlin
Programms ist eine solche Funktion. Diesen Code kann man auch einfach
in die Kotlin Shell kopieren und dann aufrufen.

#+begin_example
>>> fun main() {
...     println("Hello world")
... }
>>> main()
Hello world
#+end_example


Wenn wir diesen Code in der Datei HelloWorld.kt abspeichern und dann
den Compiler folgendermaßen aufrufen:
#+begin_src sh
> kotlinc HelloWorld.kt 
#+end_src
sehen wir, dass eine Java Class Datei und ein Meta-Inf Verzeichnis mit
der Datei main.kotlin.module erzeugt wurde:
#+begin_example
.:
HelloWorld.kt  HelloWorldKt.class  META-INF

./META-INF:
main.kotlin_module
#+end_example
Die Datei ~main.kotlin_module~ ist dabei ein Hilfskonstrukt, das dem
Kotlin Compiler hilft, Aufrufe von top-level Funktionen beim Linken
auszulösen. Wir müssen uns nicht weiter um diese Datei kümmern.

Ein Dekompilieren der Class Datei mit javap zeigt, dass aus
Kompatibilitätsgründen mit Java auch die klassische ~public static void
main(String[] args)~ Methode erzeugt worden ist. 
#+begin_example
> javap HelloWorldKt.class 

Compiled from "HelloWorld.kt"
public final class HelloWorldKt {
  public static final void main();
  public static void main(java.lang.String[]);
}
#+end_example
Diese ist wegen der Nutzung des Java Laufzeitsystem notwendig und wird
genutzt, um die Methode ~void main()~ aufzurufen, die für die
top-level ~main()~ Funktion erzeugt wurde. Aufgerufen wird das
Programm mit dem Java Interpreter und bei diesem Aufruf wird natürlich die
~void main(String[] args)~ Methode aufgerufen:
#+begin_src sh
java HelloWorldKt
#+end_src
Wir sehen im Aufruf und auch der dekompilierten Klasse, dass die
Klasse ~HelloWorldKt~ im Java ByteCode erzeugt wurde. Diese Klassen,
deren Namen sich ergeben aus dem Dateinamen und dem Suffix Kt werden
genutzt, um den Code der top-level Kotlin Funktionen aufzunehmen.

Es kann auch ganz klassisch die main Methode von Java in Kotlin
genutzt werden. 
#+begin_src kotlin :exports both

fun main(args: Array<String>) {
    println(args.contentToString())
}

main(arrayOf("Eins","Zwei"))
#+end_src

#+RESULTS:
: [Eins, Zwei]
: res7: kotlin.String = >>> 

Wenn man jetzt versucht, eine Kotlin Datei mit der klassischen main
Methode zu kompilieren und per Java Interpreter auszuführen, wird man
eine Fehlermeldung erhalten, obwohl das Beispiel in der Kotlin Shell funktioniert:
#+begin_example
> java HelloWorldKt
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at HelloWorldKt.main(HelloWorld.kt)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more

#+end_example
Grund dafür ist, dass Kotlin eine eigene Laufzeitbibliothek besitzt,
die wir im Programm durch die Nutzung der ~Array~ Klasse referenzieren,
aber das Java Laufzeitsystem diese Bibliothek im Normalfall nicht
kennt. Ein einfacher Weg das Problem zu umgehen, ist die Nutzung des
Programms kotlin, das im Kommandozeilen Paket von Kotlin enthalten ist
und die Einbindung des Laufzeitsystems übernimmt:
#+begin_example
> kotlin HelloWorldKt Eins Zwei
[Eins, Zwei]
#+end_example
Es kann natürlich auch der Java Interpreter genutzt werden, wenn man
die passende Bibliothek aus dem Kotlin Paket mit einbindet:
#+begin_example
> java -classpath ~/programme/kotlinc/lib/kotlin-stdlib.jar:. HelloWorldKt Eins Zwei
[Eins, Zwei]
#+end_example

Eine andere Alternative für stand-alone Programme ist, das Bauen einer
Jar Datei, die das Laufzeitsystem von Kotlin enthält:
#+begin_example
> kotlinc -include-runtime HelloWorld.kt -d HelloWorld.jar
> java -jar HelloWorld.jar Eins Zwei
[Eins, Zwei]
#+end_example
An der Größe der Jar Datei von etwa 1,5 MByte erkennt man gleich, dass
hier etwas mehr Code als der aus dem Beispiel mit abgelegt wurde. Es
sollte klar sein, dass die ~-include-runtime~ Option nicht bei der
Erstellung von Bibliotheken genutzt werden sollte, da die Runtime von
Kotlin jeweils nur im Code von lauffähigen Programmen benötigt wird
und wie oben gezeigt auch über die Referenz der passenden Runtime
Bibliothek eingebunden werden kann.

* Elementare Datentypen und Ausdrücke

Bevor wir komplexere Konstrukte von Kotlin ansehen, müssen wir einige
Grundzüge der Programmiersprache betrachten. 

** Lokale Variablen

Wir betrachten hier nur lokale Variablen in Code Blöcken wie z.B.
in Funktionen. Sogenannte Properties die analog definiert werden und
auf top-level Ebene und in Klassen verwendet werden können, haben
erweiterte Möglichkeiten und werden später betrachtet.

Das Schlüsselwort ~var~ leitet eine Variablendeklaration ein. Wie man
es erwartet ist der Wert einer solchen Variable änderbar. In den
folgenden Beispielen verwenden wir den Typ ~Int~, der erwartungsgemäß
Integer Zahlen repräsentiert.
#+begin_src kotlin :exports both
fun main() {
  var a: Int = 1    // Deklaration mit Typangabe und Initialisierung
  var b = 2         // Typ Inferenz 
  var c: Int        // Deklaration ohne Initialisierung
  c = 3             // spätere Initialisierung
  println("a = ${a}, b = ${b}, c = ${c}") 
  a++
  b++
  c++
  println("a = ${a}, b = ${b}, c = ${c}")
}

main()
#+end_src

#+RESULTS:
: a = 1, b = 2, c = 3
: a = 2, b = 3, c = 4

Zunächst muss man festhalten, dass in Kotlin die Typen mit einem
Doppelpunkt abgetrennt nach den Bezeichnern stehen. Das gilt dann auch
für Rückgabewerte von Funktionen, wie wir später sehen werden.

Wir sehen zu Beginn der ~main~ Funktion die gleichzeitige Deklaration
und Zuweisung der Variablen ~a~, die Deklaration und Initialisierung
der Variablen ~b~ ohne Typangabe und die Deklaration der mit Typangabe
der Variable ~c~ mit späterer Initialierung der Variablen. 

Bei der Variablen ~b~ wurde der Typ ~Int~ per Typ Inferenz von Kotlin
selber bestimmt, ohne dass der Programmierer dies angeben musste. 

Anhand der Nutzung der top-level Funktion ~println~ können wir auch
sehen, dass in Kotlin Strings standardmäßig Variablen Interpolation
erlauben.

Das Schlüsselwort ~val~ leitet eine einmal beschreibbare Variable
ein. Also eher vergleichbar mit einer Konstanten. Es gibt auch noch
das Schlüsselwort ~const~, das im Zusammenspiel mit einer ~val~
Variablen eingesetzt werden kann und eine sofortige Zuweisung
erzwingt, worauf wir aber nicht weiter eingehen, da ~const~ recht
inkonsistent nur an wenigen Stellen verwendet werden kann.

#+begin_src kotlin :exports both
fun main() {
  val a: Int = 1
  val b = 2
  val c: Int      // Initialisierung kann auch bei val verzögert sein
  c = 3
  
  println("a = ${a}, b = ${b}, c = ${c}")
  // c = 4           nicht erlaubt, Compiler meldet Fehler!!
}

main()
#+end_src

#+RESULTS:
: a = 1, b = 2, c = 3


** Elementare Datentypen

Anders als in Java werden in Kotlin (fast ausnahmslos) nur Objekttypen
verwendet, auch für alle elementaren Datentypen. Als Konsequenz sind
alle Operationen auf den Datentypen per Member-Funktion erreichbar,
wobei die Operationen größtenteils den aus Java bekannten gleichen.

Intern verwendet Kotlin aus Performancegründen teilweise die
primitiven Datentypen der Java VM, aber dies ist weitestgehend
unsichtbar für den Programmierer.


*** Ganzzahlige Datentypen

Es gibt die von Java bekannten vorzeichenbehafteten Typen (signed integers)
- Byte (8 Bit)
- Short (16 Bit)
- Int (32 Bit)
- Long (64 Bit)

#+begin_note
In den neueren Version von Kotlin ist experimenteller Support für
unsigned integers integriert. Wir gehen aber nicht näher darauf ein.
#+end_note

Bei Belegung von Variablen mit Literalen und fehlender Typangabe wählt
Kotlin im Standardfall den Typ ~Int~ aus. Falls der Wertebereich aber
nicht ausreichend ist für das Literal wird ~Long~ gewählt. Man kann den
Type ~Long~ aber auch per Suffic ~L~ an dem Zahlenliteral erzwingen.

#+begin_src kotlin :exports both
val byte: Byte = 1 
val short: Short = 128
val int: Int = 32768
val long: Long = 2147483647
val int1 = 10 // Int als default hergeleiteter Typ
val long1 = 2147483647 // long, da Wertebereich Int überschreitet
val long2 = 8L // per L Suffix wird Long als Typ erzwungen

long2.toString(2) // Zahlen sind Objekte, 8 wird als Zahl zur Basis 2 ausgegeben
#+end_src

#+RESULTS:
: kotlin.String = 1000

*** Gleitkommazahlen Datentypen

Analog zum vorherigen Abschnitt gibt es auch bei den Gleitkommazahlen
die beiden von Java bekannten Typen ~Float~ und ~Double~.

#+begin_src kotlin :exports both
val double : Double = 0.8
val pi = 3.14
val pif = 6.28f // Suffix f führt zu Float Type anstatt zum default von Double
println("${pi.hashCode()} ${pif.hashCode()}")
#+end_src

#+RESULTS:
: 300063655 1086911939

*** Booleans

Auch hier gibt es keine großen Überraschungen.

#+begin_src kotlin exports: both
val myTrue: Boolean = true
val myFalse: Boolean = false

println(myTrue || myFalse)
#+end_src

#+RESULTS:
: true

*** Zeichen/Characters

Hier gibt es ebenfalls keine Überraschungen im Vergleich zu Java.

#+begin_src kotlin export: both
val charA: Char = 'a'
val charSpecial = '\n'
val charB: Char = 'b'
println("${charA} ${charSpecial} ${charB}")
#+end_src

#+RESULTS:
: a 
:  b

*** Zeichenketten/Strings

Strings sind wiederum sehr ähnlich zu Java aufgebaut. Es gibt
zusätzlich zu den normalen Strings auch die sogenannten Raw Strings,
die mehrzeilig sein können und keine Escape Sequenzen umsetzen.
#+begin_note
Die in Java 13 eingeführten Raw Strings unterscheiden sich relativ
stark der Kotlin Variante: Interpretatio von Escape Sequenzen und
automatische Behandlung von Einrückungen.
#+end_note

#+begin_src kotlin :exports both
val rawString = """
    \n\n\t
    
    ein Test
""".trimIndent()

println(rawString)

println("\n\n")

val withoutMargin1 = """ABC
                |123
                |456""".trimMargin()

println(withoutMargin1)
#+end_src

#+RESULTS:
: \n\n\t
: 
: ein Test
: 
: 
: 
: ABC
: 123
: 456

Die Funktionen ~trimIndent()~ und ~trimMargin()~ entfernen die
Einrückungen der inneren Zeilen samt Löschen der ersten und letzten
Zeile.

In normalen wie auch in Raw Strings wird String Interpolation
unterstützt.
#+begin_src kotlin :exports both
val s = "2 + 3 = ${2+3}"
println(s)
val sr = """
2${'$'} + 3${'$'} = ${2+3}${'$'}

4${'$'} + 5${'$'} = ${4+5}${'$'}
"""
println(sr)
#+end_src

#+RESULTS:
: 2 + 3 = 5
: 
: 2$ + 3$ = 5$
: 
: 4$ + 5$ = 9$

*** Arrays

Zur Darstellung von Arrays wird die generische Klasse ~Array~
verwendet. Diese Klasse bietet auch eine Vielzahl nützlicher Member
Funktionen an (Sortierung, Suche, Slicing, ...). Analog wie bei Java
kann die Länge eines Arrays nicht verändert werden. 

Zum Erzeugen von Arrays gibt die beiden Wege über die ~arrayOf()~
Funktion und über einen Konstruktor der ~Array~ Klasse:
#+begin_src kotlin :exports both
val stringArray : Array<String> = arrayOf("1","2")
println("Länge: ${stringArray.size}")
val stringArray2 = Array(4){ i -> i.toString()}
stringArray2[2]
#+end_src

#+RESULTS:
: Länge: 2
: res10: kotlin.String = 2
: res11: kotlin.String = >>> 

#+begin_src kotlin exports: both
fun arrayTest() : Unit {
val stringArray : Array<String> = arrayOf("1", "2")
println("Zugriff über eckige Klammern Operator: ${stringArray[0] == "1"}")
stringArray.sort()
// Arrays haben eine feste Länge, so dass bei einigen Funktionen auf Arrays neue Arrays erzeugt werden:
val stringArray2 = stringArray.plus("3")
// === ermittelt die Objektidentität, == die strukturelle Identität
println("Sind die Arrays identisch: ${stringArray === stringArray2}")
// == entspricht dem Vergleich mit der equals() Member Funktion
println("Sind die Arrays gleich: ${stringArray == arrayOf("1","2")}")
println("Sind die Arrays gleich: ${arrayOf("1","2").contentDeepEquals(stringArray)}")
stringArray.forEach { s -> print(s) }
println()
println("----------")
stringArray2.forEach { s -> print(s) }
println()
println("Arrays schneiden: ${stringArray2.sliceArray(0..1).contentDeepEquals(stringArray)}")
}
arrayTest()
#+end_src

#+RESULTS:
: Zugriff über eckige Klammern Operator: true
: Sind die Arrays identisch: false
: Sind die Arrays gleich: false
: Sind die Arrays gleich: true
: 12
: ----------
: 123
: Arrays schneiden: true
: res1: kotlin.String = >>> 

Zusätzlich gibt es noch die Möglichkeit Arrays von primitiven Typen zu nutzen.
Der wichtigste Grund für deren Verwendung ist, dass zur Laufzeit Speicherplatz
gespart wird, da die Inhalte dieser Arrays aus primitiven Typen gebildet werden.
Diese Arrays sind nicht von der Klasse ~Array~ in irgendeiner Form abgeleitet,
besitzen aber ähnlichen Funktionsumfang.

#+begin_src kotlin exports: both
val intarray : IntArray = intArrayOf(1,2,3)
intarray.forEach{ ia -> println(ia) }
println()
val doublearray : DoubleArray = doubleArrayOf(1.0, 2.0, 3.0)
doublearray.forEach{ da -> println(da) }
#+end_src

#+RESULTS:
: 1
: 2
: 3
: 
: 1.0
: 2.0
: 3.0

** Ausdrücke und Anweisungen

Da Kotlin sich viele Anleihen aus dem Bereich der funktionalen
Programmierung genommen, sind anders als in Java angepasste Varianten
von Anweisungen auch in Form von Ausdrücken verwendbar. Im Kotlin
Sprachgebrauch sind alle üblichen Anweisungen imperativer,
objekt-orientierter Programmiersprachen Ausdrücke. 

#+begin_note
Anmerkung: Ausdrücke liefern Werte - Anweisungen nicht, sie
ändern nur den Kontrollfluss.
#+end_note

*** If Anweisung/Ausdruck

Wenn ein ~if~ Ausdruck in keinem Zweig explizit einen Wert liefert,
dann ist der Typ des gesamten ~if~ Ausdrucks ~Unit~ (vergleichbar mit
void in Java) und hat somit keinen Wert. In dieser Form gleicht die
Verwendung der einer Anweisung. 

#+begin_src kotlin :exports both
// etwas Heck-meck, um den Typ des if Ausdrucks zu sehen
var value = 4
val aFun = fun() = if (2 < 1) value = 5 else value = 3
aFun
#+end_src

#+RESULTS:
: {Comparable<*> & Number} = 1

Wenn die beiden Zweige von if unterschiedliche Typen
zurückgeben, wir der Gesamtrückgabe-Typ so bestimmt, dass ein
möglichst eng eingegrenzter Typ ausgewählt wird. Im Extremfall kann
der Typ dann auch ~Any~ sein.
#+begin_src kotlin :exports both
if (1 < 2) 1 else 1.0
#+end_src

#+RESULTS:
: {Comparable<*> & Number} = 1

Wenn der Wert des ~if~ Ausdrucks verwendet wird, muss der ~else~ Zweig
immer vorhanden sein.
#+begin_src kotlin :exports source
val aValue = if (1 < 2) 5 else 4 // OK
aValue = if (1 < 2) 5 // Fehler
#+end_src

*** When Anweisung/Ausdruck

Ein ~when~ Ausdruck ähnelt der ~switch~ Anweisung wie man sie aus Java
kennt. Analog dazu werden in einem ~when~ Ausdruck die angegebenen
Bedingungen in der Reihenfolge ihres Auftretens geprüft und der Zweig
der Bedingung ausgeführt, die als erste zu ~true~ evaluiert wird. Der
optionale ~else~ Zweig wird ausgeführt, falls keine der Bedingungen
zutrifft. Der ~else~ Zweig muss zwingend angegeben werden, wenn ~when~
als Ausdruck verwendet wird und der Compiler nicht erkennen kann, dass
eine der Bedingungen zutreffen muss, was z.B. bei der Prüfung auf
~Enum~ der Fall sein kann.

#+begin_src kotlin :exports both
val x = 5
val y = 4
// Verwendung als Ausdruck:
val result = 
when (x) {
  1    -> "ist eins"
  2, 3 -> "ist zwei oder drei"
  y + 1 -> "eins mehr als y" // Bedingung kann Ausdruck sein
  else -> "weiß nicht" // else zwingend wegen Nutzung als Ausdruck
}
result
#+end_src

#+RESULTS:
: kotlin.String = eins mehr als y

Die Bedingungen in dem ~when~ Ausdruck können auch recht komplex sein:
#+begin_src kotlin :exports both
val x = 5
when (x) {
  in 1..10 -> println("in range")
  !in 10..20 -> println("out of range")
  is Number -> println("ist vom Typ String") // Typ muss zuweisungskompatibel mit x sein
  // hier lassen wir else mal weg, was aber schlechter Stil ist
}
#+end_src

#+RESULTS:
: in range

Der ~when~ Ausdruck lässt sich auch ohne Eingabewert verwenden und
stellt damit ein mächtigeres ~if~ Konstrukt zur Verfügung:
#+begin_src kotlin :exports both
val x = 5
val y = 3
when {
  x > 4 -> "x größer 4"
  y < 4 -> "y kleiner 4"
  else "weiß nicht"
}
#+end_src



* Grundkonstruktion von Programmen

** Kein static Modifier und die Folgen
Kotlin unterstützt auf Sprachenebene nicht den Modifier ~static~, der
in Java zur Zuordnung von Variablen und Methoden zu Klassen genutzt
werden kann. Dies hat für einige Konstrukte in Kotlin gesorgt, um
Funktionalitäten nachzubilden, für die in Java ~static~ verwendet
wurde. Die Details dieser Konstrukte sehen wir uns später an.

- Statt static Member Variablen gibt es top-level Properties.
- Statt static Methoden gibt es top-level Funktionsdefinitionen.
- Für Singletons gibt es die Möglichkeit top-level Quasi-Klassen zu
  definieren, von denen genau ein Objekt existiert. Dieses Konstrukt
  wird auch einfach Object genannt.
- Um Objekten einer Klasse die Möglichkeit zu geben, um auf
  Klassenebene Strukturen und Funktionen zu nutzen, gibt es das
  Konstrukt ~companion object~, das in einer Klasse definiert sein
  kann. Darüber kann man zum Beispiel ein Factory Method Pattern
  abbilden. Ein ~companion object~ ist also eine Art Singleton, das
  explizit einer Klasse zugeordnet ist.

** Top Level Konstrukte der Programmiersprache


*** Funktionen

Funktionen treten in den Variationen
- Top-level Funktion
- Lokale Funktion innerhalb einer anderen Funktion (Local Function)
- Member Funktion eines Typs (Member Function)
- Funktionsliterale (function liberal) sind Lambda Ausdrücke und
  anonyme Funktionen
auf.

**** Basisfunktionalität

Die Parameter einer Funktion müssen explizit angegebene Typen haben.

#+begin_src kotlin :exports both
// Parameter können default Werte haben:
fun test1(a:Int, b:Int = 4) : Int {
  return a+b
}
// wie üblich
println(test1(1,2))
// mit Benennung der Parameter:
println(test1(b = 3, a = 1))
// Parameter mit default Werten können entfallen, so lange 
// die Zuordnung der Parameter gewährleistet ist:
println(test1(1))

// Wenn eine Funktion keine Rückgabe per return tätigt
// ist der Rückgabetyp Unit bzw. muss es sein.
// Übergabe eines Lambda Ausdrucks an eine Funktion:
fun testLambda(foo : Int, la : (Int) -> Unit) : Unit {
  la(foo)
 }
testLambda(45, {it -> println(it)})
// Wenn eine Funktion nur einen Ausdruck berechnet kann eine Kurzform
// ohne return Anweisung und geschweiften Klammern verwendet werden:
fun shortTest(a: Int, b: Int) : Int = a + b
println(shortTest(20,40))

// Variable Anzahl von Parametern werden als Array übergeben:
fun varTest(vararg ts: Int) : Int {
  return ts.fold(0,{acc:Int, i:Int -> acc + i})
}
println(varTest(1,2,3))
#+end_src

Funktionen können auch Infix Notation nutzen, wenn die Funktion eine
Member Funktion (oder Extension Funktion) ist, nur einen Parameter hat
und dieser nicht ~vararg~ ist.

#+begin_src kotlin :export source
class FunctionExample (val iMem : Int) {
    infix fun ifxFun(param : Int) : Int {
        return iMem + param;
    }
}

fun main() {
    val funEx = FunctionExample(200)
    println(funEx ifxFun 4)
}
#+end_src

Funktionen können auch generisch sein:
#+begin_src kotlin :exports both
fun <T> testToList(item: T): List<T> {
  return listOf(item)
}
testToList(12)
#+end_src

#+RESULTS:
: kotlin.collections.List<kotlin.Int> = [12]

**** Higher Order Functions

Higher Order Functions bekommen Funktionen als Parameter oder geben
eine Funktion zurück. Um dies zu ermöglichen, muss der Typ einer
Funktion angegeben werden können, um z.B. damit den Typ eines
Funktionsparameters festzulegen.

#+begin_src kotlin :exports both
fun <T> countDelegate(liste: List<T>, counter: (List<T>) -> Int) : Int{
  return counter(liste)
}

countDelegate(listOf(1,2,3), List<Int>::size)
#+end_src

#+RESULTS:
: kotlin.Int = 3

Um Funktionen als Werte für Funktionstypen zu bekommen gibt es
verschiedene Varianten:
- Über einen Lambda Ausdruck:
  #+begin_src kotlin :exports both
  val testFun: (Int) -> Unit = { a -> println("Testwert: " + a) }
  println(::testFun)
  testFun(42)
  #+end_src

  #+RESULTS:
  : val Line_2.testFun: (kotlin.Int) -> kotlin.Unit
  : Testwert: 42
  Alternativ könnte die Lambda Definition auch so aussehen, wobei
  Kotlin hier Typinferenz anwendet soweit möglich:
  #+begin_src kotlin :exports source
  val testFun = { a:Int -> println("Testwert: " + a) }
  #+end_src

- Über eine anonyme Funktion:
  #+begin_src kotlin :exports both
  val toInt: (String) -> Int = fun(s: String): Int { return s.toIntOrNull() ?: 0 }
  println(::toInt)
  toInt("1")
  #+end_src

  #+RESULTS:
  : val Line_8.toInt: (kotlin.String) -> kotlin.Int
  : kotlin.Int = 1

- Über eine Referenz auf eine bestehende Funktionsdefinition:
  #+begin_src kotlin :exports both
  fun apply(c: String, f: (String) -> Int) : Int = f(c)
  apply("42",String::toInt)
  #+end_src

  #+RESULTS:
  : kotlin.Int = 42
  Eine Funktionsreferenz kann dabei auf eine top-level Funktion
  (::topLevelFunction), Member oder Extension Funktion (String::toInt)
  zeigen.

- Zudem gibt es noch den etwas esoterischen Fall, dass eine Klasse
  einen Funktionstyp implementiert, was bedeutet, dass sie ein
  Interface mit einer Funktion implementiert, die dem Funktionstyp
  entspricht, wobei die Funktion den Operator ~()~ überlädt (Operator
  Overloading), der auf die Funktion ~invoke()~ abgebildet wird:
  #+begin_src kotlin :exports both
  class IntTransformer: (Int) -> Int {
    override operator fun invoke(x: Int): Int = x + 1
  }

  val intFunction: (Int) -> Int = IntTransformer()
  intFunction(5)
  #+end_src

  #+RESULTS:
  : kotlin.Int = 6

Lambda Ausdrücke und anonyme Funktionen werden als Funktionsliterale
bezeichnet und können direkt als Ausdruck für die Übergabe von
Funktionen verwendet werden.

Ein Lamba Ausdruck ist immer in geschweiften Klammen angegeben und
benötigt im Gegensatz zu einer Funktion mit Block kein exlizites
return Statement. Der letzte Wert in der Abarbeitung ist der
Rückgabewert. Die return Anweisung kann aber trotzdem verwendet werden.

#+begin_src kotlin :exports both
val lambda = { a:Int, b:Int ->
        val c = a + b
        val b = c*2
        b*3
    }
println(lambda(2,3))
// Default Parametername in einem Lambda ist it und die
// Definition des Parameternamens kann dann entfallen:
val sum = arrayOf(1,2,3).map { it * 2 }.sum()
println(sum)
// ein Lambda kann als letzter Parameter auch nach
// den Parameterklammern übergeben werden:
val foldValue = arrayOf(1,2,3).fold(10){acc, e -> acc * e}
println(foldValue)
#+end_src

#+RESULTS:
: 30
: 12
: 60

Anonyme Funktionen unterscheiden sich zu Lambdas folgendermaßen:
- Mit einer anonymen Funktion kann man den Typ des Rückgabewertes
  angeben, falls nötig.
- Eine ~return~ Anweisung in einem Lambda springt aus der umgebenden
  Funktion zurück, bei einer anonymen Funktion nur aus dieser selber.

Die Closure eines Lambda Ausdrucks, anonymen Funktion, lokalen
Funktion oder Object Ausdrucks umfasst alle aus dem äußeren Scope
zugreifbaren Variablen. Beispiel:
#+begin_src kotlin :exports both
var sum = 0
val changeSum = { sum = sum + 3 }
changeSum()
println(sum)
#+end_src

#+RESULTS:
: 3

*** Properties	

Top-level Properties unterscheiden sich von den lokalen Variablen
bzw. den Properties in Klassen. Implementierungstechnisch werden
top-level Properties in JVM Klassen eingebettet, die für die Source
jeweiligen Kotlin Source Dateien erzeugt werden. 

Ein top-level Property muss immer bei Deklaration initialisiert
werden, da kein Konstruktor wie in einer Klasse die Initialisierung
erledigen kann, bevor der erste Zugriff stattfinden kann. Eine
Initialisierung ist auch dann notwendig, wenn der Typ der Property als
Nullable angegeben ist. Analog bezüglich der Initialisierung zu
top-level Properties verhalten sich auch Properties in Companion
Objects. Auch diese müssen bei Deklaration initialisiert werden.

*** Interfaces

*** Klassen

Klassen können enthalten:
- Konstruktoren und Initialisierungsblöcke
- Member Funktionen
- Properties
- Eingebettete Klassen (nested classes) und innere Klassen (inner
  classes sind nested classes mit Zugriff auf das äußere Objekt)
- Objekt Deklarationen (z.B. um Singletons zu realisieren oder
  Companion Objekte)


**** Properties in Klassen
Properties in Klassen sind analog zu definieren wie top-level Properties.

#+begin_src kotlin :exports both
class Test {
  var test : String = "Variabler Wert"
  val rtest = "ReadOnly Wert mit type inference"
}

val t = Test()
t.test + " " + t.rtest
#+end_src

Properties in Klassen können analog zu top-level Properties ihre
default-Getter und -Setter überschreiben:
#+begin_src kotlin :exports both
class Test {
  var test : Int = 2
  get() = field + 1 // Nutzung des backing field
  set(value) {
    field += value
  }
}
val t = Test()
t.test = 2 // impliziter Call des Setter
t.test     // impliziter Call des Getter
#+end_src


#+RESULTS:
: kotlin.Int = 5

Man kann auch die Sichtbarkeit der Getter und Setter steuern:
#+begin_src kotlin :exports both
class Test {
  var test : Int = 2
  get() = field + 1 // Nutzung des backing field
  private set // auch ohne Implementierung nur für die Sichtbarkeit
}
val t = Test()
//t.test = 2 würde jetzt einen Fehler ergeben
t.test     // impliziter Call des Getter
#+end_src

#+RESULTS:
: kotlin.Int = 3


**** Konstruktoren

Über den sogenannten primary constructor kann man Klassen schön
kompakt formulieren:
#+begin_src kotlin :exports both
class Test (var test : Int) { // Konstruktor Parameter und Property gleichzeitig definiert
}
val t = Test(2)
t.test
#+end_src

#+RESULTS:
: kotlin.Int = 2

Dieses Beispiel maximal länglich aber mit primary constructor wäre so zu formulieren:
#+begin_src kotlin :exports both
class Test constructor(testparam : Int) {
  var test : Int = testparam
}
val t = Test(2)
t.test
#+end_src

#+RESULTS:
: kotlin.Int = 2

Ein secondary constructor muss den primary constructor immer aufrufen,
damit der primary constructor bei Objektinitialisierung immer zuerst
ausgeführt wird. Dies muss vor allen wegen initializer Blocks und
Property Wertzuweisung passieren:
#+begin_src kotlin :exports both
class Test constructor(testparam : Int) {
  var test : Int = testparam
  var secTest : Int = 4

  constructor (testparam: Int, secparam : Int) : this(testparam) {
    secTest = secparam
  }
}
val t = Test(4,4)
t.test + t.secTest
#+end_src

#+RESULTS:
: kotlin.Int = 8

Falls kein primary constructor definiert wird, erzeugt Kotlin einen
default primary constructor, welcher auch automatisch bei Aufruf eines
secondary constructors ausgeführt wird:
#+begin_src kotlin :exports both
class Test {
  var test : Int
  init {
    test = 8
  }
  constructor (testparam : Int) {
    test += testparam
  }
}
val t = Test(2)
t.test
#+end_src

#+RESULTS:
: kotlin.Int = 10

**** Vererbung

Die Entsprechung zur Klasse ~Object~ in Java ist in Kotlin Klasse
~Any~. Wenn explizit keine Superklasse bei der Definition einer Klasse
angegeben ist, erbt diese von ~Any~.

Einige Regeln zur Vererbung erläutern wir in dem folgenden Beispiel.

#+begin_src kotlin :exports source
/**
 * Ohne das Schlüsselwort <code>open</code> wäre die Klasse
 * nicht ableitbar, d.h. final.
 * Der primary constructor führt das Property value ein.
 */
open class ClassExample(var value : Int) {
    /**
     * Auch Properties können überschrieben werden, sind aber ebenfalls final im Default Fall:
     * Der default Wert kann sich ändern oder ein <code>val</code> kann
     * zum <code>var</code> werden, aber nicht andersherum.
     * Auch die <code>get</code> und <code>set</code> Methoden können
     * beim überschreiben geändert oder neu eingeführt oder weggelassen werden.
     */
    open val propVal : Double = Double.MAX_VALUE

    /**
     * Damit die Member Funktione überschrieben werden kann, muss auch sie mit <code>open</code>
     * eingeleitet werden.
     */
    open fun changeValue(changer : Int) {
        value += changer
    }
}

/**
 * Der primary constructor der abgeleiteten Klasse darf das Property value nicht mehr einführen,
 * muss es aber initialisieren - daher fehlt die <em>var</em> Angabe, der Wert wird
 * aber trotzdem initialisiert.
 * Ohne primary constructor müssen die secondary constructors für die Initialierung
 * von <code>value</value> sorgen.
 * Wir markieren diese Klasse wiederum mit <code>open</code> denn ansonsten wäre sie automatisch
 * final.
 */
open class DerivedClassExample(valueParam: Int) : ClassExample(valueParam) {
    val notChangeAble : Int = valueParam

    /**
     * Wir überschreiben hier das Property. Wichtig ist noch, dass diese Änderung des Propertys
     * nicht aktiv ist, wenn die Basisklasse initialisiert wird, was vor der abgeleiteten Klasse
     * passiert.
     */
    override val propVal: Double
        get() = super.propVal + 4.0

    /**
     * Der secondary constructor ruft den primary auf, da hier ein Aufruf <code>super(valueParam)</code>
     * nicht erlaubt ist. Das wäre dann der Fall, wenn es in der abgeleiteten Klasse keinen primary
     * constructor geben würde - siehe nächste Klasse.
     */
    constructor(valueParam: Int, notChanged: Int) : this(valueParam) {
        value
    }

    /**
     * Wir überschreiben die Member Funktion <code>changeValue</code> hier.
     * Ein überschreibende Member Funktion ist in weiteren abgeleiteten Klassen ebenfalls
     * überschreibbar, außer man markiert ist mit <code>final</code>
     */
    override fun changeValue(changer: Int) {
        // nicht notwendigerweise bisheriges Verhalten nutzen:
        super.changeValue(changer)
        // zusätzliche Aktion:
        value *= changer
    }
}

/**
 * Diese abgeleitete Klasse hat keinen primary constructor und muss daher im secondary die
 * Basisklasse über den <coce>super(valueParam)</code> Aufruf initialisieren.
 * Die Angabe von <code>final</code> bei der Klasse ist überflüssig, da ohne die Markierung
 * <code>open</code> die Klasse automatisch final ist.
 */
final class SecondDerivedClassExample : ClassExample {
    constructor(valueParam : Int) : super(valueParam)
}
#+end_src

**** Interfaces

Interfaces in Kotlin können Member Funktionen deklarieren als auch
implementieren. Im ersten Fall ist die Funktion dann abstrakt markiert
und in allen Fällen sind die Funktionen überschreibbar.

Interfaces können aber im Gegensatz zu abstrakten Klassen keinen
Zustand speichern. Es können aber Properties definiert sein, die im
Interface selber maximal Konstanten abbilden oder generell abstrakt
sind und in den implementierenden Klassen dann überschrieben werden.

Ein Beispiel für die Nutzung von Interfaces ist unten angegeben:
#+begin_src kotlin :exports source
interface InterfaceExample {
    /**
     * Dieses Property ist abstrakt.
     */
    val firstProp : Int

    val secondProp : Int
    get() = 42

    /**
     * Diese Funktion ist abstrakt.
     */
    fun firstInterfaceFunction(param1 : Double) : Int

    /**
     * Diese Funktion
     */
    fun secondInterfaceFunction(param1 : Int, param2 : Double) : Int {
        return param1 * firstInterfaceFunction(param2)
    }
}

/**
 * Wir überschreiben das erste Property mit dem primary constructor
 * das erste Property des Interfaces.
 */
class ImplementInterface(override val firstProp : Int = 55) : InterfaceExample {

    override val secondProp: Int
        get() = super.secondProp + firstProp

    /**
     * Wir überschreiben die abstrakte Funktion.
     */
    override fun firstInterfaceFunction(param1: Double): Int {
        return param1.toInt()
    }

    /**
     * Wir überschreiben auch nicht notwendigerweise die implementierte Funktion.
     */
    override fun secondInterfaceFunction(param1: Int, param2: Double): Int {
        return super.secondInterfaceFunction(param1, param2) + 2
    }
}
#+end_src

**** Extensions

Kotlin bietet auch die Möglichkeit zu Klassen Memberfunktionen
hinzuzufügen, obwohl diese Klassen eigentlich nicht änderbar sind, da
sie zum Beispiel aus einer von extern eingebundenen Bibliothek
stammen. Analog lassen sich auch Properties hinzufügen, wobei hier
aber kein separater Zustand (also ein ~backing field~ dazu fehlt)
speicherbar ist und der Wert des Properties entweder konstant oder
errechnet ist.

Beispiele sind unten angegeben:
#+begin_src kotlin :exports source
/**
 * Wir werden diese Klasse per Extensions erweitern (auch wenn wir die Klasse
 * hier direkt im Zugriff haben und nicht auf diesen Mechanismus angewiesen wären.
 */
class ExtensionExample(var memberVar : Int = 4) {
}

/**
 * Erweiterung um diese Funktion.
 */
fun ExtensionExample.extendFun() {
    this.memberVar = 5
}

/**
 * Erweiterung um dieses Property
 */
val ExtensionExample.extMemberVar : Double
get() = 4.5

fun main() {
    val ext = ExtensionExample()
    println(ext.extMemberVar)
    println(ext.extendFun())
}
#+end_src

** Organisation von Source Code

In diesem Abschnitt beschäftigen wir uns mit der Frage, wie man die
zuvor erwähnten top-level Sprachkonstrukte organisiert, um eine
strukturierte Programmentwicklung zu ermöglichen.

*** Modularisierung

Bisher haben wir in den Beispielen keine Konstrukte zur
Modularisierung von Code verwendet. Kotlin hat hierbei diese
Möglichkeiten:
- Package
- Module 

Modules spielen eine Rolle bei der Sichtbarkeit von ~internal~
Deklarationen und ansonsten bei einigen Backends für den Kotlin
Code. Wir werden dieses Konstrukt daher nicht weiter betrachten.


*** Aufbau einer Source Code Datei

*** Organisation der Dateiablage

*** Sichtbarkeitsregeln

* Erstellen einer Domain Specific Language
Einige Sprachfeatures von Kotlin wurden im Hinblick auf die Erstellung
von Domain Specific Languages eingeführt bzw. optimiert. Dazu zählen:
- Function type with receiver: Hiermit können Funktionsliterale
  erzeugt werden, die Objekte eines in der Signatur der Funktion
  angegebenen Typs als ~this~ Referenz in der Implementierung der
  Funktion nutzen können. D.h. die Funktion hat die Möglichkeiten wie
  eine Member Funktion des Typs, ohne aber Teil der Typdefinition zu
  sein, da sie ein Funktionsliteral ist. 
- Ein Lambda Ausdruck als letzter Parameter einer Funktion kann
  außerhalb der runden Klammern der Parameterliste übergeben
  werden. Der Lamba Ausdruck sieht dann so aus, als würde er als Block
  zum Funktionsaufruf gehören, wird aber in der eigentlichen Funktion
  verwendet.
- Funktionen, die in Infix Notation aufgerufen werden können.
- Die Möglichkeit Operatoren zu überladen (Operator Overloading).
- Die Möglichkeit Funktionen mit benannten Parameter aufzurufen.


#+begin_src kotlin :exports both
class DslTestbed {
    class Outer {
        var innerNodes = mutableListOf<Inner>()

        fun inner(init: Inner.() -> Unit){
            val child = Inner()
            child.init()
            innerNodes.add(child)
        }

        fun show() : String {
            val lines = mutableListOf<String>()
            lines.add("Outer node")
            innerNodes.forEach(){
                lines.add(it.show())
            }
            return lines.joinToString(separator = "\n")
        }
    }

    class Inner() {
        val innerNodes = mutableListOf<InnerMost>()

        fun innerMost(weight: Double){
            val child = InnerMost(weight)
            innerNodes.add(child)
        }

        fun show() : String {
            val lines = mutableListOf<String>()
            lines.add("Inner node: ".prependIndent("  "))
            innerNodes.forEach(){
                lines.add(it.show())
            }
            return lines.joinToString(separator = "\n")
        }
    }

    class InnerMost(val weight: Double) {
        fun show() : String {
            return "InnerMost node: ".prependIndent("    ") + String.format("%+07.2g",weight)
        }
    }

    companion object {
        fun outer(init: Outer.() -> Unit) : String {
            val outer = Outer()
            outer.init()
            return outer.show()
        }
    }
}

fun main() {
    val structure =
        DslTestbed.outer {
            inner {
                innerMost(weight = 45.8889)
                innerMost(weight = -1938.4883)
            }
            inner {
                innerMost(weight = 22.0048)
                innerMost(weight = 234234.23423)
            }
        }
    println(structure)
}
#+end_src

#+RESULTS:
